export const SCREENS = {
  WELCOME: "WELCOME",
  PIN_CODE: "PIN_CODE",
  PIN_CODE_CONFIRM: "PIN_CODE_CONFIRM",
  DOWNLOAD_KEYSTORE_FILE: "DOWNLOAD_KEYSTORE_FILE",
  SEED: "SEED",
  ADDRESS: "ADDRESS",
  UNLOCK: "UNLOCK",
  ADDRESS_WORK: "ADDRESS_WORK"
};
